<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/1
 * Time: 16:17
 */

class Product{
    protected $name;
    protected $price;
    protected $stock;
    protected function ShowInfo(){
        echo "<br />商品名称是：{$this->name}";
        echo "<br />商品价格是：{$this->price}";
    }
    function __construct($name,$price,$stock)
    {
        $this->name = $name;
        $this->price = $price;
        $this->stock = $stock;
    }
}
class Mobile extends Product{
    private $brand;
    private $chandi;
    function __construct($name,$price,$stock,$brand,$chandi)
    {
        parent::__construct($name,$price,$stock);
        $this->brand = $brand;
        $this->chandi = $chandi;
    }
    function ShowInfo(){
        parent::ShowInfo();
        echo "<br />品牌是：{$this->brand}";
        echo "<br />产地是：{$this->chandi}";
        echo "<br />库存是：{$this->stock}";
    }
}
class Books extends Product{
    private $author;
    private $press;
    function __construct($name,$price,$stock,$author,$press)
    {
        parent::__construct(name,$price,$stock);
        $this->author = $author;
        $this->press = $press;
    }
    function ShowInfo()
    {
        parent::ShowInfo(); // TODO: Change the autogenerated stub
        echo "<br />作者是：{$this->author}";
        echo "<br />出版社是：{$this->press}";
        echo "<br />库存是：{$this->stock}";
    }
}
$m1 = new Mobile('联想3280','1208',100,'Lenovo','北京上地信息产业 基地');
$m1 -> ShowInfo();
?>